# Generated by Django 2.1.5 on 2019-02-28 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ad')),
            ],
            options={
                'verbose_name': 'il',
                'verbose_name_plural': 'iller',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ad')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities.City', verbose_name='il')),
            ],
            options={
                'verbose_name': 'ilçe',
                'verbose_name_plural': 'ilçeler',
            },
        ),
    ]
