# Generated by Django 2.1.5 on 2019-02-28 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={'verbose_name': 'il / ilçe', 'verbose_name_plural': 'il / ilçe'},
        ),
    ]
