# Generated by Django 2.1.5 on 2019-01-16 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20190116_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='education',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'yok'), (1, 'ilk öğrenim'), (2, 'lise'), (3, 'üniversite'), (4, 'yüksek lisans'), (5, 'doktora')], null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'erkek'), ('f', 'kadın'), ('qm', 'kuir erkek'), ('qf', 'kuir kadın')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
