# Generated by Django 2.1.5 on 2019-01-17 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_session_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('order', 'id'), 'verbose_name': 'Soru', 'verbose_name_plural': 'Sorular'},
        ),
        migrations.AddField(
            model_name='answer',
            name='answer',
            field=models.SmallIntegerField(choices=[(-2, 'kesinlikle katılmıyorum'), (-1, 'katılmıyorum'), (0, 'kararsızım'), (1, 'katılıyorum'), (2, 'kesinlikle katılıyorum')], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='questons',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='polls.Question'),
            preserve_default=False,
        ),
    ]
