# Generated by Django 2.1.5 on 2019-01-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20190117_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='started',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
