# Generated by Django 2.1.5 on 2019-01-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20190117_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.SmallIntegerField(choices=[(0, 'kesinlikle katılmıyorum'), (1, 'kısmen katılmıyorum'), (2, 'kararsızım'), (3, 'kısmen katılıyorum'), (4, 'kesinlikle katılıyorum')], default=0),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('poll', 'question')},
        ),
    ]
