# Generated by Django 2.1.5 on 2019-01-23 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_media_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'cevap', 'verbose_name_plural': 'cevaplar'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'kategori', 'verbose_name_plural': 'kategoriler'},
        ),
        migrations.AlterModelOptions(
            name='media',
            options={'verbose_name': 'medya', 'verbose_name_plural': 'medya'},
        ),
        migrations.AlterModelOptions(
            name='poll',
            options={'verbose_name': 'anket', 'verbose_name_plural': 'anketler'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('order', 'id'), 'verbose_name': 'soru', 'verbose_name_plural': 'sorular'},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'verbose_name': 'oturum', 'verbose_name_plural': 'oturumlar'},
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.SmallIntegerField(choices=[(0, 'kesinlikle katılmıyorum'), (1, 'kısmen katılmıyorum'), (2, 'kararsızım'), (3, 'kısmen katılıyorum'), (4, 'kesinlikle katılıyorum')], default=0, verbose_name='cevap'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Poll', verbose_name='anket'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Question', verbose_name='soru'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='kategori adı'),
        ),
        migrations.AlterField(
            model_name='media',
            name='active',
            field=models.BooleanField(default=True, verbose_name='yayında'),
        ),
        migrations.AlterField(
            model_name='media',
            name='categories',
            field=models.ManyToManyField(to='polls.Category', verbose_name='kategoriler'),
        ),
        migrations.AlterField(
            model_name='media',
            name='content',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='içerik'),
        ),
        migrations.AlterField(
            model_name='media',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='tanım'),
        ),
        migrations.AlterField(
            model_name='media',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='bağlantı'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='yaş'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='education',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'yok'), (1, 'ilk öğrenim'), (2, 'lise'), (3, 'üniversite'), (4, 'yüksek lisans'), (5, 'doktora')], null=True, verbose_name='eğitim durumu'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='ended',
            field=models.DateTimeField(blank=True, null=True, verbose_name='bitiş'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'erkek'), ('f', 'kadın'), ('qm', 'kuir erkek'), ('qf', 'kuir kadın')], max_length=2, null=True, verbose_name='cinsiyet'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='score',
            field=models.FloatField(blank=True, null=True, verbose_name='skor'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.Session', verbose_name='oturum'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='started',
            field=models.DateTimeField(auto_now_add=True, verbose_name='başlangıç'),
        ),
        migrations.AlterField(
            model_name='question',
            name='active',
            field=models.BooleanField(default=True, verbose_name='yayında'),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.Category', verbose_name='kategori'),
        ),
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='sıralama'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=250, verbose_name='soru'),
        ),
        migrations.AlterField(
            model_name='session',
            name='active',
            field=models.BooleanField(default=True, verbose_name='yayında'),
        ),
        migrations.AlterField(
            model_name='session',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='eklenme tarihi'),
        ),
        migrations.AlterField(
            model_name='session',
            name='name',
            field=models.CharField(max_length=100, verbose_name='oturum'),
        ),
        migrations.AlterField(
            model_name='session',
            name='slug',
            field=models.SlugField(verbose_name='bağlantı adı'),
        ),
    ]
