# Generated by Django 2.1.5 on 2019-01-24 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20190123_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='lifestyle',
            field=models.CharField(blank=True, choices=[('m', 'modern'), ('g', 'geleneksel muhafazakar'), ('d', 'dindar muhafazakar')], max_length=1, null=True, verbose_name='hayat tarzı'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'erkek'), ('f', 'kadın'), ('qm', 'LGBTI erkek'), ('qf', 'LGBTI kadın')], max_length=2, null=True, verbose_name='cinsiyet'),
        ),
    ]
