# Generated by Django 2.1.5 on 2019-02-03 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_auto_20190124_0448'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_f',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='soru (kadın versiyonu)'),
        ),
    ]
