# Generated by Django 2.1.5 on 2019-02-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_auto_20190226_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='hometown_size',
            field=models.CharField(blank=True, choices=[('k', 'Köy'), ('i', 'Kasaba / İlçe'), ('s', 'Şehir'), ('m', 'Büyükşehir / Metropol')], max_length=1, null=True, verbose_name='büyüdüğünüz yer'),
        ),
        migrations.AddField(
            model_name='poll',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('b', 'Bekar'), ('s', 'Sözlü / Nişanlı'), ('e', 'Evli'), ('d', 'Dul'), ('a', 'Boşanmış')], max_length=1, null=True, verbose_name='medeni durum'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='education',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Diplomasız okur'), (1, 'İlkokul mezunu'), (2, 'İlköğretim / Ortaokul mezunu'), (3, 'Lise mezunu'), (4, 'Yüksekokul mezunu'), (5, 'Lisans mezunu'), (6, 'Yüksek lisans'), (7, 'Doktora')], null=True, verbose_name='eğitim durumu'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'erkek'), ('f', 'kadın'), ('g', 'LGBTI erkek'), ('l', 'LGBTI kadın')], max_length=1, null=True, verbose_name='cinsiyet'),
        ),
    ]
