# Generated by Django 2.1.5 on 2019-02-28 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_auto_20190227_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.PositiveSmallIntegerField(verbose_name='cevap'),
        ),
    ]
