# Generated by Django 2.1.5 on 2019-02-28 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_auto_20190228_0811'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='cevap'),
        ),
        migrations.AddField(
            model_name='question',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.QuestionSource', verbose_name='kaynak'),
        ),
    ]
