# Generated by Django 2.1.5 on 2019-02-28 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_auto_20190228_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='woman_attendee_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='kadın katılımcı oranı'),
        ),
    ]
