# Generated by Django 2.1.5 on 2019-02-28 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_auto_20190228_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='employee_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='çalışan sayısı'),
        ),
        migrations.AddField(
            model_name='session',
            name='woman_employee_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='kadın çalışan sayısı'),
        ),
        migrations.AlterField(
            model_name='session',
            name='attendee_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='etkinlik katılımcı sayısı'),
        ),
        migrations.AlterField(
            model_name='session',
            name='woman_attendee_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='etkinlik kadın katılımcı sayısı'),
        ),
    ]
