# Generated by Django 2.1.5 on 2019-02-28 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
        ('polls', '0021_auto_20190228_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities.City', verbose_name='il'),
        ),
        migrations.AddField(
            model_name='session',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities.District', verbose_name='ilçe'),
        ),
    ]
