# Generated by Django 2.1.5 on 2019-02-28 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
        ('polls', '0022_auto_20190228_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='city',
        ),
        migrations.RemoveField(
            model_name='session',
            name='district',
        ),
        migrations.AddField(
            model_name='session',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities.District', verbose_name='yer'),
        ),
    ]
