# Generated by Django 2.1.5 on 2019-02-28 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0002_auto_20190228_1732'),
        ('polls', '0023_auto_20190228_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities.City', verbose_name='il'),
        ),
        migrations.AlterField(
            model_name='session',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='yer'),
        ),
    ]
