# Generated by Django 2.1.5 on 2019-03-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0025_auto_20190228_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='age',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='yaşın'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='poll',
            name='education',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Diplomasız okur'), (1, 'İlkokul mezunu'), (2, 'İlköğretim / Ortaokul mezunu'), (3, 'Lise mezunu'), (4, 'Yüksekokul mezunu'), (5, 'Lisans mezunu'), (6, 'Yüksek lisans'), (7, 'Doktora')], default=0, help_text='son bitirdiğin okul', verbose_name='eğitim durumun'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='poll',
            name='gender',
            field=models.CharField(choices=[('m', 'Erkek'), ('f', 'Kadın')], default='m', max_length=1, verbose_name='cinsiyetin'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='poll',
            name='hometown_size',
            field=models.CharField(choices=[('k', 'Köy'), ('i', 'Kasaba / İlçe'), ('s', 'Şehir'), ('m', 'Büyükşehir / Metropol')], default='k', max_length=1, verbose_name='büyüdüğün yer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='poll',
            name='lifestyle',
            field=models.CharField(blank=True, choices=[('m', 'Modern'), ('g', 'Geleneksel muhafazakar'), ('d', 'Dindar muhafazakar')], max_length=1, null=True, verbose_name='hayat tarzın'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='marital_status',
            field=models.CharField(choices=[('b', 'Bekar'), ('s', 'Sözlü / Nişanlı'), ('e', 'Evli'), ('d', 'Dul'), ('a', 'Boşanmış')], default='b', max_length=1, verbose_name='medeni durumun'),
            preserve_default=False,
        ),
    ]
