# Generated by Django 2.1.5 on 2019-04-01 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0026_auto_20190307_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='content',
        ),
        migrations.AlterField(
            model_name='media',
            name='url',
            field=models.URLField(default='http://localhost', verbose_name='bağlantı'),
            preserve_default=False,
        ),
    ]
