# Generated by Django 2.1.5 on 2019-05-07 09:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0028_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
