# Generated by Django 3.1.5 on 2021-01-14 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0030_auto_20191014_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='education',
            field=models.PositiveSmallIntegerField(choices=[(0, 'No formal education'), (1, 'Primary School'), (2, 'Secondary School'), (3, 'High School'), (4, 'College'), (5, 'University'), (6, 'Masters'), (7, 'Doctorate / PhD'), (8, 'Student')], help_text='Final degree', verbose_name='Education'),
        ),
    ]
